FROM maven:3.9.11-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests


FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 80

CMD ["sh", "-c", "exec /opt/java/openjdk/bin/java -jar /app/app.jar --server.port=${PORT:-80}"]