spring:
  application:
    name: mySchedule

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 5000
      initialization-fail-timeout: 5000

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:80}

jwt:
  secret: ${JWT_SECRET}